Repository SurajSG23/Job-Portal, pull requests merged in 2025-08, with the labels that each got.

#83 Theme Toggle button added
  components/employer.css
  components/employer.html
  index.html
  style.css
Labels: gssoc25, level-3, hacktoberfest

#96 Fixed the Job description box
  components/employer.css
  components/employer.html
Labels: gssoc25, hacktoberfest

#98 Add Container for Dynamic Job Listings to Enable Infinite Scro
  index.html
  script.js
  style.css
Labels: gssoc25, level-2, hacktoberfest

#176 Added background to the Sign Up page
  signup.html
Labels: gssoc25, level-1, hacktoberfest

#284 Masthead Page – Highlight the Job Portal’s Vision & Mission
  index.html
  masthead.html
Labels: gssoc25, level-2, hacktoberfest

#351 Enhance Footer
  components/about.html
Labels: gssoc25, level-1, hacktoberfest
